spring.application.name=usuario-mascotas

# ===============================
#  CONFIG BD MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/mascotas_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
#  CONFIG JPA / HIBERNATE
# ===============================

# Crear tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Mejor formato del SQL
spring.jpa.properties.hibernate.format_sql=true

# Dialecto recomendado para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



spring.security.user.name=admin
spring.security.user.password=admin